name: 'Deploy EC2 with PSQL Client'
description: 'Deploy an EC2 instance and install PostgreSQL client'
inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
    default: 'ap-southeast-2'
  ami_id:
    description: 'AMI ID for the EC2 instance'
    required: true
  instance_type:
    description: 'Instance type for the EC2 instance'
    required: true
    default: 't2.micro'
  key_name:
    description: 'Name of the SSH key pair'
    required: true
  instance_name:
    description: 'Name tag for the EC2 instance'
    required: true
    default: 'Demo Instance'
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy EC2 Instance
      uses: demodso/org-action-ec2-deploy@v1
      with:
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_region: ${{ inputs.aws_region }}
        ami_id: ${{ inputs.ami_id }}
        instance_type: ${{ inputs.instance_type }}
        key_name: ${{ inputs.key_name }}
        instance_name: ${{ inputs.instance_name }}
      id: ec2-deploy

    - name: Install PSQL Client
      uses: demodso/org-action-ansible-psql@v1
      with:
        target_host: ${{ steps.ec2-deploy.outputs.instance_public_ip }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_private_key: ${{ inputs.ssh_private_key }}

outputs:
  instance_id:
    description: "ID of the created EC2 instance"
    value: ${{ steps.ec2-deploy.outputs.instance_id }}
  instance_public_ip:
    description: "Public IP of the created EC2 instance"
    value: ${{ steps.ec2-deploy.outputs.instance_public_ip }}